#
# Copyright (C) 2024-2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/ossi

PRODUCT_COPY_FILES += \
    vendor/realme/ossi/proprietary/odm/bin/hw/vendor-oplus-hardware-touch-V2-service:$(TARGET_COPY_OUT_ODM)/bin/hw/vendor-oplus-hardware-touch-V2-service \
    vendor/realme/ossi/proprietary/odm/bin/hw/vendor.oplus.hardware.biometrics.fingerprint@2.1-service_uff:$(TARGET_COPY_OUT_ODM)/bin/hw/vendor.oplus.hardware.biometrics.fingerprint@2.1-service_uff \
    vendor/realme/ossi/proprietary/odm/bin/hw/vendor.oplus.hardware.charger-V6-service:$(TARGET_COPY_OUT_ODM)/bin/hw/vendor.oplus.hardware.charger-V6-service \
    vendor/realme/ossi/proprietary/odm/bin/hw/vendor.oplus.hardware.cryptoeng@1.0-service:$(TARGET_COPY_OUT_ODM)/bin/hw/vendor.oplus.hardware.cryptoeng@1.0-service \
    vendor/realme/ossi/proprietary/odm/bin/hw/vendor.oplus.hardware.displaypanelfeature-service:$(TARGET_COPY_OUT_ODM)/bin/hw/vendor.oplus.hardware.displaypanelfeature-service \
    vendor/realme/ossi/proprietary/odm/bin/hw/vendor.oplus.hardware.vibrator-service:$(TARGET_COPY_OUT_ODM)/bin/hw/vendor.oplus.hardware.vibrator-service \
    vendor/realme/ossi/proprietary/odm/etc/init/vendor-oplus-hardware-touch-V2-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor-oplus-hardware-touch-V2-service.rc \
    vendor/realme/ossi/proprietary/odm/etc/init/vendor.oplus.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/realme/ossi/proprietary/odm/etc/init/vendor.oplus.hardware.charger-V6-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.charger-V6-service.rc \
    vendor/realme/ossi/proprietary/odm/etc/init/vendor.oplus.hardware.cryptoeng@1.0-service_FDE.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.cryptoeng@1.0-service_FDE.rc \
    vendor/realme/ossi/proprietary/odm/etc/init/vendor.oplus.hardware.displaypanelfeature-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.displaypanelfeature-service.rc \
    vendor/realme/ossi/proprietary/odm/etc/init/vibrator-default.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vibrator-default.rc \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/android.hardware.power.stats-service.oplus.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/android.hardware.power.stats-service.oplus.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/android.hardware.power.stats.IPowerStats-V2.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/android.hardware.power.stats.IPowerStats-V2.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/device_manifest_communication_center_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/device_manifest_communication_center_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/device_manifest_subsys.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/device_manifest_subsys.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_engineer_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_engineer_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_misc_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_misc_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_module_virtual_audio.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_module_virtual_audio.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplusSensor_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplusSensor_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplus_cammidasservice_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplus_cammidasservice_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplus_charger_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplus_charger_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplus_cryptoeng.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplus_cryptoeng.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplus_displaypanelfeature_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplus_displaypanelfeature_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplus_face.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplus_face.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplus_fido.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplus_fido.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplus_fido2.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplus_fido2.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplus_fingerprint_aidl_v3.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplus_fingerprint_aidl_v3.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplus_gameopt.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplus_gameopt.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplus_ifaa.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplus_ifaa.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplus_location_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplus_location_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplus_sendextcamcmd.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplus_sendextcamcmd.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplus_stability_project_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplus_stability_project_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_oplus_virtualdevice_audio_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_oplus_virtualdevice_audio_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_performance_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_performance_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_powermonitor_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_powermonitor_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_rpmh_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_rpmh_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_touch_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_touch_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/manifest_transmessage_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/manifest_transmessage_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/oplus_aidl_wifi_service_device_manifest.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/oplus_aidl_wifi_service_device_manifest.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/vendor.oplus.hardware.olc2_aidl.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/vendor.oplus.hardware.olc2_aidl.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/vendor.oplus.hardware.urcc-service.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/vendor.oplus.hardware.urcc-service.xml \
    vendor/realme/ossi/proprietary/odm/etc/vintf/manifest/vibrator-default.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/vibrator-default.xml \
    vendor/realme/ossi/proprietary/odm/lib64/liboplusvibratoreffect.so:$(TARGET_COPY_OUT_ODM)/lib64/liboplusvibratoreffect.so \
    vendor/realme/ossi/proprietary/odm/lib64/vendor.oplus.hardware.charger-V6-ndk.so:$(TARGET_COPY_OUT_ODM)/lib64/vendor.oplus.hardware.charger-V6-ndk.so \
    vendor/realme/ossi/proprietary/odm/lib64/vendor.oplus.hardware.cryptoeng-V1-ndk.so:$(TARGET_COPY_OUT_ODM)/lib64/vendor.oplus.hardware.cryptoeng-V1-ndk.so \
    vendor/realme/ossi/proprietary/odm/lib64/vendor.oplus.hardware.displaypanelfeature-V1-ndk.so:$(TARGET_COPY_OUT_ODM)/lib64/vendor.oplus.hardware.displaypanelfeature-V1-ndk.so \
    vendor/realme/ossi/proprietary/odm/lib64/vendor.oplus.hardware.touch-V2-ndk.so:$(TARGET_COPY_OUT_ODM)/lib64/vendor.oplus.hardware.touch-V2-ndk.so \
    vendor/realme/ossi/proprietary/odm/lib64/vendor.oplus.hardware.vibrator-V1-ndk.so:$(TARGET_COPY_OUT_ODM)/lib64/vendor.oplus.hardware.vibrator-V1-ndk.so \
    vendor/realme/ossi/proprietary/vendor/bin/fuelgauged:$(TARGET_COPY_OUT_VENDOR)/bin/fuelgauged \
    vendor/realme/ossi/proprietary/vendor/bin/fuelgauged_nvram:$(TARGET_COPY_OUT_VENDOR)/bin/fuelgauged_nvram \
    vendor/realme/ossi/proprietary/vendor/bin/init.insmod.sh:$(TARGET_COPY_OUT_VENDOR)/bin/init.insmod.sh \
    vendor/realme/ossi/proprietary/vendor/bin/modprobe:$(TARGET_COPY_OUT_VENDOR)/bin/modprobe \
    vendor/realme/ossi/proprietary/vendor/bin/nvram_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/nvram_daemon \
    vendor/realme/ossi/proprietary/vendor/bin/sh:$(TARGET_COPY_OUT_VENDOR)/bin/sh \
    vendor/realme/ossi/proprietary/vendor/bin/swap_enable.sh:$(TARGET_COPY_OUT_VENDOR)/bin/swap_enable.sh \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.audio.service-aidl.mediatek:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.audio.service-aidl.mediatek \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.bluetooth-service-mediatek:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.bluetooth-service-mediatek \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.boot-service.mtk:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.boot-service.mtk \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.drm-service.clearkey:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.drm-service.clearkey \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.gatekeeper-service.trustonic:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gatekeeper-service.trustonic \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.gnss-service.mediatek:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gnss-service.mediatek \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.graphics.allocator-V2-service-mediatek:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.graphics.allocator-V2-service-mediatek \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.graphics.composer@3.3-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.graphics.composer@3.3-service \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.lights-service.mediatek:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.lights-service.mediatek \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.media.c2-mediatek:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.media.c2-mediatek \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.media.c2-mediatek-64b:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.media.c2-mediatek-64b \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.memtrack-service.mediatek:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.memtrack-service.mediatek \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.security.keymint@3.0-service.trustonic_norkp:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.security.keymint@3.0-service.trustonic_norkp \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.sensors-service.multihal:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.sensors-service.multihal \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.thermal-service.mediatek:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.thermal-service.mediatek \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.usb-aidl-service.mediatekv1.0:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.usb-aidl-service.mediatekv1.0 \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.usb.gadget-aidl-service.mediatekv1.0:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.usb.gadget-aidl-service.mediatekv1.0 \
    vendor/realme/ossi/proprietary/vendor/bin/hw/android.hardware.wifi-service-lazy:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.wifi-service-lazy \
    vendor/realme/ossi/proprietary/vendor/bin/hw/camerahalserver:$(TARGET_COPY_OUT_VENDOR)/bin/hw/camerahalserver \
    vendor/realme/ossi/proprietary/vendor/bin/hw/hostapd:$(TARGET_COPY_OUT_VENDOR)/bin/hw/hostapd \
    vendor/realme/ossi/proprietary/vendor/bin/hw/mtkfusionrild:$(TARGET_COPY_OUT_VENDOR)/bin/hw/mtkfusionrild \
    vendor/realme/ossi/proprietary/vendor/bin/hw/vendor.mediatek.hardware.mtkpower-service.mediatek:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.mediatek.hardware.mtkpower-service.mediatek \
    vendor/realme/ossi/proprietary/vendor/bin/hw/vendor.mediatek.hardware.nvram-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.mediatek.hardware.nvram-service \
    vendor/realme/ossi/proprietary/vendor/bin/hw/vendor.mediatek.hardware.pq_aidl-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.mediatek.hardware.pq_aidl-service \
    vendor/realme/ossi/proprietary/vendor/bin/hw/wpa_supplicant:$(TARGET_COPY_OUT_VENDOR)/bin/hw/wpa_supplicant \
    vendor/realme/ossi/proprietary/vendor/etc/init.insmod.mt6877.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/init.insmod.mt6877.cfg \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.audio.service-aidl.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.audio.service-aidl.mediatek.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.bluetooth-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth-service-mediatek.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.boot-service.mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.boot-service.mtk.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.drm-service.clearkey.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.clearkey.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.gatekeeper-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service.trustonic.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.graphics.allocator-V2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator-V2-service-mediatek.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.graphics.composer@3.3-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.composer@3.3-service.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.media.c2-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2-mediatek.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.security.keymint@3.0-service.trustonic_norkp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint@3.0-service.trustonic_norkp.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.sensors-service-multihal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors-service-multihal.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.usb-aidl-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb-aidl-service.mediatek.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.usb.gadget-aidl-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb.gadget-aidl-service.mediatek.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.wifi-service-lazy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi-service-lazy.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/android.hardware.wifi.supplicant-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi.supplicant-service.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/hostapd.android.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hostapd.android.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/lights-mtk-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lights-mtk-default.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/memtrack-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/memtrack-mediatek.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/thermal-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/thermal-mediatek.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/vendor.mediatek.hardware.mtkpower@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mtkpower@1.0-service.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram-sevice.rc \
    vendor/realme/ossi/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq_aidl-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq_aidl-service.rc \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.audio.effect.service-aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.audio.effect.service-aidl.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.audio.service-aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.audio.service-aidl.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.bluetooth-service-mediatek.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.bluetooth-service-mediatek.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.boot-service.mtk.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.boot-service.mtk.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.drm-service.clearkey.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.drm-service.clearkey.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.gatekeeper-service.trustonic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.gatekeeper-service.trustonic.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.neuralnetworks-shim-service-mtk.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.neuralnetworks-shim-service-mtk.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.security.keymint-service.trustonic_norkp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.security.keymint-service.trustonic_norkp.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.security.secureclock-service.trustonic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.security.secureclock-service.trustonic.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.trustonic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.security.sharedsecret-service.trustonic.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.sensors-multihal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.sensors-multihal.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.tetheroffload-V1-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.tetheroffload-V1-service.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.usb-aidl-service.mediatek.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.usb-aidl-service.mediatek.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.usb.gadget-aidl-service.mediatek.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.usb.gadget-aidl-service.mediatek.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.wifi-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.wifi-service.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.wifi.hostapd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.wifi.hostapd.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/android.hardware.wifi.supplicant.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.wifi.supplicant.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/bluetooth_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/bluetooth_audio.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/CommandService.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/CommandService.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/em_hal_service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/em_hal_service.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/gnss-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/gnss-default.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/gnss-mtk.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/gnss-mtk.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/lights-mtk-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/lights-mtk-default.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/manifest_allocator.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_allocator.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/manifest_apuware_apusys_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_apuware_apusys_aidl.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/manifest_apuware_utils_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_apuware_utils_aidl.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/manifest_apuware_xrp_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_apuware_xrp_aidl.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/manifest_hwcomposer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_hwcomposer.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/manifest_media_c2_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_media_c2_default.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/manifest_module_binaural_record.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_module_binaural_record.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/manifest_soter_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_soter_aidl.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/mapper.mediatek.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/mapper.mediatek.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/memtrack-mediatek.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/memtrack-mediatek.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/mtkpower_applist-mtk-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/mtkpower_applist-mtk-default.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/mtk_lbs_service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/mtk_lbs_service.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/power-mediatek.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/power-mediatek.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/thermal-mediatek.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/thermal-mediatek.xml \
    vendor/realme/ossi/proprietary/vendor/etc/vintf/manifest/vendor.oplus.hardware.wifi.supplicant.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vendor.oplus.hardware.wifi.supplicant.xml \
    vendor/realme/ossi/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/realme/ossi/proprietary/vendor/firmware/connfem.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/connfem.cfg \
    vendor/realme/ossi/proprietary/vendor/firmware/conninfra.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/conninfra.cfg \
    vendor/realme/ossi/proprietary/vendor/firmware/gt9896s_firmware_6877v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6877v01_1080x2280.bin \
    vendor/realme/ossi/proprietary/vendor/firmware/gt9896s_firmware_6877v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6877v01_1080x2300.bin \
    vendor/realme/ossi/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/realme/ossi/proprietary/vendor/firmware/soc5_0_ram_bt_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc5_0_ram_bt_1_1_hdr.bin \
    vendor/realme/ossi/proprietary/vendor/firmware/soc5_0_ram_mcu_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc5_0_ram_mcu_1_1_hdr.bin \
    vendor/realme/ossi/proprietary/vendor/firmware/soc5_0_ram_wmmcu_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc5_0_ram_wmmcu_1_1_hdr.bin \
    vendor/realme/ossi/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/realme/ossi/proprietary/vendor/firmware/WIFI_RAM_CODE_soc5_0_1_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc5_0_1_1.bin \
    vendor/realme/ossi/proprietary/vendor/lib64/android.hardware.health-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.health-V1-ndk.so \
    vendor/realme/ossi/proprietary/vendor/lib64/android.hardware.health-V3-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.health-V3-ndk.so \
    vendor/realme/ossi/proprietary/vendor/lib64/libcustom_nvram.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcustom_nvram.so \
    vendor/realme/ossi/proprietary/vendor/lib64/libmtk-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtk-ril.so \
    vendor/realme/ossi/proprietary/vendor/lib64/libnvram.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvram.so \
    vendor/realme/ossi/proprietary/vendor/lib64/libnvram_sec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvram_sec.so \
    vendor/realme/ossi/proprietary/vendor/lib64/libril.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril.so \
    vendor/realme/ossi/proprietary/vendor/lib64/vendor.mediatek.hardware.nvram-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.mediatek.hardware.nvram-V1-ndk.so \
    vendor/realme/ossi/proprietary/vendor/lib64/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLES_mali.so \
    vendor/realme/ossi/proprietary/vendor/lib64/hw/hwcomposer.mt6877.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/hwcomposer.mt6877.so \
    vendor/realme/ossi/proprietary/vendor/lib64/hw/sensors.mt6877.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/sensors.mt6877.so

